function Compare-AutomateControlStatus {
<#
.Synopsis
   Takes computer objects from Get-AutomateComputer, compares against online sessions in control and outputs an object of agents that are on in Control and Off in Automate
.DESCRIPTION
   Takes computer objects from Get-AutomateComputer, compares against online sessions in control and outputs an object of agents that are on in Control and Off in Automate
.PARAMETER ComputerObject
   ComputerObject generated by Get-AutomateComputer
.EXAMPLE
   Get-AutomateComputer -Online $False | Compare-AutomateControlStatus
.INPUTS
   Computer Object as derived from Get-AutomateComputer
.OUTPUTS
   Custom object containing online status for machines online in Control and Offline in Automate
#>
    [CmdletBinding()]
    param (
        [Parameter(ValueFromPipeline = $true)]
        $ComputerObject

    )
  
    begin {
        $Source = @"
 
using System;
using System.Management.Automation;
namespace FastSearch
{
 
    public static class Search
    {
        public static object Find(PSObject[] collection, string column, string data)
        {
            foreach(PSObject item in collection)
            {
                if (item.Properties[column].Value.ToString() == data) { return item; }
            }
 
            return null;
        }
    }
}
"@
        Add-Type -ReferencedAssemblies $Assem -TypeDefinition $Source -Language CSharp        
        $ArrayTest = @()
        $ObjectRebuild = @()
    }
  
    process {
        $ObjectRebuild += $ComputerObject
    }

    
  
    end {
        #Get all of the Control sessions
        Write-Host -ForegroundColor Green "Getting all control sessions. This may take a few minutes"
        $ControlSessions = Get-ControlSessions

        Write-Host -ForegroundColor Green "Getting all Automate Control GUIDs. This may take a few minutes"
        foreach ($computer in $ObjectRebuild) {
            $GUID = Get-ControlInfo -ComputerID $($computer | Select-Object -ExpandProperty id)
            $OnlineStatus = [FastSearch.Search]::Find($ControlSessions, "SessionID", $GUID.SessionID) | Select-Object -ExpandProperty Connected
            $Object = ""
            $Object = [pscustomobject] @{
                ComputerID = $Computer.ID
                ComputerName = $computer.ComputerName
                ClientName = $computer.client.Name
                OperatingSystem = $computer.OperatingSystemName
                OnlineStatusControl = $(If($OnlineStatus){"Online"}else{"Offline"})
                OnlineStatusAutomate = $Computer.Status
                GUID = $GUID.SessionID
            }
            $ArrayTest += $Object
                }              
        $ArrayTest | ?{($_.OnlineStatusControl -eq 'Online') -and ($_.OnlineStatusAutomate -eq 'Offline') }
    }
}
